name: Generate Snake Animation

on:
  # Runs every 6 hours
  schedule:
    - cron: "0 */6 * * *"
  # Also allows manual trigger & on push to main
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Generate Snake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ajayduraisamy
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push snake animation to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
